# Generated by Django 6.0.3 on 2026-04-07 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='monto',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Precio'),
        ),
    ]
