# Generated by Django 6.0.3 on 2026-04-07 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_factura_monto_alter_product_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Factura',
        ),
    ]
